# Generated by Django 4.2.4 on 2023-08-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resetpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='key',
            new_name='token',
        ),
    ]
