# Generated by Django 4.2.4 on 2023-08-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_key_resetpassword_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpassword',
            old_name='token',
            new_name='key',
        ),
    ]
