# Generated by Django 4.2.4 on 2023-08-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
